services:
  api:
    build: ./services/api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - mongo

  worker_py:
    build: ./services/worker_py
    env_file: .env
    depends_on:
      - redis
      - mongo

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7
    volumes:
      - ./docker-data/mongo:/data/db
    ports:
      - "27017:27017"
